[build]
target = "targets/aarch64-raspi5.json"

[target.aarch64-raspi5]
rustflags = [
  "-C", "link-arg=-Tlinker.ld",
  "-C", "link-arg=--gc-sections",
  "-C", "link-arg=--build-id=none"
]

[target.aarch64-raspi3]
rustflags = [
  "-C", "link-arg=-Tlinker.ld",
  "-C", "link-arg=--gc-sections",
  "-C", "link-arg=--build-id=none"
]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
